config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-tooling git:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-cornflower-balinese.sh
        container: qc.acc_squeaky-gamboge-duck
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-tooling find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-beige-eagle.sh
        container: qc.doc_randy-champagne-dog
      github.com/EOSC-synergy/sqaaas-tooling git:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-pink-ant.sh
        container: qc.doc_gummy-copper-koala
      github.com/EOSC-synergy/sqaaas-tooling markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-corn-spitz.sh
        container: qc.doc_nippy-cerise-toad
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-tooling licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-puce-quoll.sh
        container: qc.lic_grumpy-jade-angora
  QC.Sec:
    repos:
      github.com/EOSC-synergy/sqaaas-tooling bandit:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-cerulean-wasp.sh
        container: qc.sec_muzzy-aquamarine-chameleon
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-tooling flake8:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-brown-otter.sh
        container: qc.sty_whiny-salmon-cougar
      github.com/EOSC-synergy/sqaaas-tooling hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-goldenrod-fish.sh
        container: qc.sty_flabby-auburn-affenpinscher
      github.com/EOSC-synergy/sqaaas-tooling jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-amaranth-russel.sh
        container: qc.sty_slaphappy-asparagus-walrus
  QC.Uni:
    repos:
      github.com/EOSC-synergy/sqaaas-tooling pytest:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-gamboge-booby.sh
        container: qc.uni_whiny-olivine-albatross
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-tooling get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-burgundy-lobster.sh
        container: qc.ver_silly-red-horse
timeout: 5400
