config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-tooling git:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-xanthic-ostrich.sh
        container: qc.acc_scanty-rose-coyote
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-tooling find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-carmine-hornet.sh
        container: qc.doc_wiggy-celadon-lizard
      github.com/EOSC-synergy/sqaaas-tooling git:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-taupe-kudu.sh
        container: qc.doc_snippy-auburn-abyssinian
      github.com/EOSC-synergy/sqaaas-tooling markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-wheat-mammoth.sh
        container: qc.doc_sleepy-jade-otter
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-tooling licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-cerise-mammoth.sh
        container: qc.lic_skimpy-peach-foxhound
  QC.Sec:
    repos:
      github.com/EOSC-synergy/sqaaas-tooling bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-ecru-falcon.sh
        container: qc.sec_slimy-ivory-beaver
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-tooling flake8:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-chocolate-bat.sh
        container: qc.sty_tacky-bistre-terrier
      github.com/EOSC-synergy/sqaaas-tooling hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-cinnabar-caiman.sh
        container: qc.sty_slimy-green-panda
      github.com/EOSC-synergy/sqaaas-tooling jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-brown-rhinoceros.sh
        container: qc.sty_flabby-charcoal-seal
  QC.Uni:
    repos:
      github.com/EOSC-synergy/sqaaas-tooling pytest:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-rose-caterpillar.sh
        container: qc.uni_lovely-rust-hound
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-tooling get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-olivine-sloth.sh
        container: qc.ver_silly-cinnamon-duck
timeout: 5400
