config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/eosc-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-tooling git:
        commands:
        - /usr/bin/env sh .sqa/script.grape_aware_iguana.sh
        container: qc.acc_thistle_shy_condor
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-tooling find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lavender_respectful_seahorse.sh
        container: qc.doc_cadet_anxious_kiwi
      github.com/eosc-synergy/sqaaas-tooling git:
        commands:
        - /usr/bin/env sh .sqa/script.pumpkin_goofy_kingfisher.sh
        container: qc.doc_cinnabar_forgiving_snail
      github.com/eosc-synergy/sqaaas-tooling markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.ebony_rational_condor.sh
        container: qc.doc_ebony_ambitious_spren
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-tooling licensee:
        commands:
        - /usr/bin/env sh .sqa/script.bone_motivated_elk.sh
        container: qc.lic_ginger_courageous_koala
  QC.Sec:
    repos:
      github.com/eosc-synergy/sqaaas-tooling bandit:
        commands:
        - /usr/bin/env sh .sqa/script.royal_easygoing_pangolin.sh
        container: qc.sec_aquamarine_gentle_uakari
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-tooling flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sepia_attentive_platypus.sh
        container: qc.sty_eggplant_zany_horse
      github.com/eosc-synergy/sqaaas-tooling hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.olive_visionary_griffin.sh
        container: qc.sty_royal_innocent_cockatoo
      github.com/eosc-synergy/sqaaas-tooling jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.malachite_insightful_angelfish.sh
        container: qc.sty_brown_cheerful_piranha
  QC.Uni:
    repos:
      github.com/eosc-synergy/sqaaas-tooling pytest:
        commands:
        - /usr/bin/env sh .sqa/script.kiwi_timid_nighthawk.sh
        container: qc.uni_nutmeg_authentic_tapir
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-tooling get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flint_happy_tarantula.sh
        container: qc.ver_mulberry_reckless_camel
timeout: 5400
